### ISSUE TITLE
Maintain README.md

### ISSUE THREAD

**Issue by Prakash4844** [Prakash4844/Name-subject-to-change#5]
We need to maintain `Readme.md`
So people can see what it does and how it does.
Keep Adding Relevant info in `Readme.md`.

**Comment by SakuraBlossomTree** [comment]
I can if you want to

**Comment by Prakash4844** [comment]
Hey i have opened a discussion about it. We can discuss it there. We have decided an initial name. But we are open to further discuss it.

**Comment by SakuraBlossomTree** [comment]
okay I have posted a comment on that discussion

**Comment by Prakash4844** [comment]
@SakuraBlossomTree i am closing this issue and will be creating a discussion for maintaing Readme.md so it can be worked on continously.
